map:
  path: "/home/tulsi/rp_project/src/xy_simulator/maps/map.png"
  width: 10.0
  height: 8.0
  resolution: 0.05
   

robots:
  - name: "Bot1"
    frame_id: "map"
    initial_pose:
      x: 10.0
      y: 10.0
      theta: 0
    dimensions:
      wheel_r: 0.5
    color:
      r: 1.0
      g: 0.0
      b: 0.0
      a: 1.0
    lidar:
      num_beams: 200
      min_range: 0.1
      max_range: 15.0
    max_vel: 1


  - name: "Bot2"
    frame_id: "map"
    initial_pose:
      x: -10.0
      y: 10.0
      theta: 0
    dimensions:
      wheel_r: 0.8
    color:
      r: 1.0
      g: 1.0
      b: 0.0
      a: 1.0
    lidar:
      num_beams: 200
      min_range: 0.1
      max_range: 15.0
    max_vel: 1


