map:
  path: "/home/tulsi/rp_project/src/xy_simulator/maps/map.png"
  width: 10.0
  height: 8.0
  resolution: 0.5
   

robots:
  - name: "Bot1"
    frame_id: "map"
    initial_pose:
      x: 7.5
      y: -110.0
      theta: -1.57
    dimensions:
      wheel_r: 4
    color:
      r: 0.0
      g: 1.0
      b: 0.0
      a: 1.0
    lidar:
      num_beams: 200
      min_range: 0.1
      max_range: 60.0
    max_vel: 1

  - name: "Bot2"
    frame_id: "map"
    initial_pose:
      x: -34.0
      y: -110.0
      theta: 3.142
    dimensions:
      wheel_r: 4
    color:
      r: 0.0
      g: 0.0
      b: 1.0
      a: 1.0
    lidar:
      num_beams: 200
      min_range: 0.1
      max_range: 60.0
    max_vel: 1
